## Libraries

it is a set of functions, modules, and classes where it pre-written codes to perform some tasks

## Pandas Library

- For Data Analysis

In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (2.3.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\victus\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [5]:
students_marks = pd.read_csv(filepath_or_buffer = r"C:\Users\Victus\Downloads\jupyter-notebook\students.csv")

In [6]:
students_marks

,student_id,name,age,city,math_score,science_score,english_score
0,1,Arun,20,Chennai,85.0,78,92
1,2,Priya,21,Coimbatore,90.0,88,85
2,3,Karthik,19,Madurai,75.0,82,79
3,4,Divya,22,Chennai,88.0,91,87
4,5,Ravi,20,Salem,65.0,70,68
5,6,Meena,21,Trichy,95.0,89,93
6,7,Suresh,20,Chennai,72.0,68,75
7,8,Anitha,22,Coimbatore,80.0,85,82
8,9,Vijay,19,Madurai,60.0,55,63
9,10,Kavya,21,Salem,NaN,80,88

## 2. Numpy—numerical operation

In [7]:
import numpy as np

In [8]:
np.repeat(a= students_marks, repeats = 3 , axis = 1)

array([[1, 1, 1, 'Arun', 'Arun', 'Arun', 20, 20, 20, 'Chennai',
        'Chennai', 'Chennai', 85.0, 85.0, 85.0, 78, 78, 78, 92, 92, 92],
       [2, 2, 2, 'Priya', 'Priya', 'Priya', 21, 21, 21, 'Coimbatore',
        'Coimbatore', 'Coimbatore', 90.0, 90.0, 90.0, 88, 88, 88, 85, 85,
        85],
       [3, 3, 3, 'Karthik', 'Karthik', 'Karthik', 19, 19, 19, 'Madurai',
        'Madurai', 'Madurai', 75.0, 75.0, 75.0, 82, 82, 82, 79, 79, 79],
       [4, 4, 4, 'Divya', 'Divya', 'Divya', 22, 22, 22, 'Chennai',
        'Chennai', 'Chennai', 88.0, 88.0, 88.0, 91, 91, 91, 87, 87, 87],
       [5, 5, 5, 'Ravi', 'Ravi', 'Ravi', 20, 20, 20, 'Salem', 'Salem',
        'Salem', 65.0, 65.0, 65.0, 70, 70, 70, 68, 68, 68],
       [6, 6, 6, 'Meena', 'Meena', 'Meena', 21, 21, 21, 'Trichy',
        'Trichy', 'Trichy', 95.0, 95.0, 95.0, 89, 89, 89, 93, 93, 93],
       [7, 7, 7, 'Suresh', 'Suresh', 'Suresh', 20, 20, 20, 'Chennai',
        'Chennai', 'Chennai', 72.0, 72.0, 72.0, 68, 68, 68, 75, 75, 75],
       [8, 8, 8, 'Anitha', 'Anitha', 'Anitha', 22, 22, 22, 'Coimbatore',
        'Coimbatore', 'Coimbatore', 80.0, 80.0, 80.0, 85, 85, 85, 82, 82,
        82],
       [9, 9, 9, 'Vijay', 'Vijay', 'Vijay', 19, 19, 19, 'Madurai',
        'Madurai', 'Madurai', 60.0, 60.0, 60.0, 55, 55, 55, 63, 63, 63],
       [10, 10, 10, 'Kavya', 'Kavya', 'Kavya', 21, 21, 21, 'Salem',
        'Salem', 'Salem', nan, nan, nan, 80, 80, 80, 88, 88, 88]],
      dtype=object)

In [9]:
students_mark_updated = pd.DataFrame( data= np.repeat(a= students_marks, repeats = 3 , axis = 1))

In [10]:
students_mark_updated

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1,1,1,Arun,Arun,Arun,20,20,20,Chennai,...,Chennai,85.0,85.0,85.0,78,78,78,92,92,92
1,2,2,2,Priya,Priya,Priya,21,21,21,Coimbatore,...,Coimbatore,90.0,90.0,90.0,88,88,88,85,85,85
2,3,3,3,Karthik,Karthik,Karthik,19,19,19,Madurai,...,Madurai,75.0,75.0,75.0,82,82,82,79,79,79
3,4,4,4,Divya,Divya,Divya,22,22,22,Chennai,...,Chennai,88.0,88.0,88.0,91,91,91,87,87,87
4,5,5,5,Ravi,Ravi,Ravi,20,20,20,Salem,...,Salem,65.0,65.0,65.0,70,70,70,68,68,68
5,6,6,6,Meena,Meena,Meena,21,21,21,Trichy,...,Trichy,95.0,95.0,95.0,89,89,89,93,93,93
6,7,7,7,Suresh,Suresh,Suresh,20,20,20,Chennai,...,Chennai,72.0,72.0,72.0,68,68,68,75,75,75
7,8,8,8,Anitha,Anitha,Anitha,22,22,22,Coimbatore,...,Coimbatore,80.0,80.0,80.0,85,85,85,82,82,82
8,9,9,9,Vijay,Vijay,Vijay,19,19,19,Madurai,...,Madurai,60.0,60.0,60.0,55,55,55,63,63,63
9,10,10,10,Kavya,Kavya,Kavya,21,21,21,Salem,...,Salem,NaN,NaN,NaN,80,80,80,88,88,88